baseURL = "https://blog.doseextra.com"
DefaultContentLanguage = "pt-br"
languageCode = "pt-br"
title = "Blog Dose Extra"
theme = "zinestrao"

[params]
  siteName = "Blog Dose Extra"
  description = "Cultura, produção multimídia, design e desenvolvimento web na Serra Gaúcha."
  twitter = "@sitedoseextra"
  TwitterURL = "//twitter.com/sitedoseextra"
  facebook = "//facebook.com/doseextra"
  email = "blog@doseextra.com"
  telegram = "//t.me/joinchat/AAAAAAfihmNSCdp0GZ1a_g"
  messenger = "//www.messenger.com/t/1625905931054179"
  instagram = "//instagram.com/doseextra"
  gplus = ""
  ItunesSum = "Desenvolvimento web, design, midias sociais, Software Livre e bastidores de uma produtora multimídia."
  ItunesDes = "Desenvolvimento web, design, midias sociais, Software Livre e bastidores de uma produtora multimídia."
  ItunesImg = "img/podcast/capadoseextra.png"

[permalinks]
  podcast = "/:filename"
  revista = "/:filename"
  paginas = "/:filename"
  artigos = "/:filename"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "author"
